# Generated by Django 3.1.5 on 2021-01-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dod', models.DateField(null=True)),
                ('image', models.CharField(max_length=1000)),
                ('children', models.ManyToManyField(related_name='_member_children_+', to='application.Member')),
            ],
        ),
    ]
